name: Build and Push Docker images

on:
    push:
    workflow_dispatch: 

jobs:
    docker-login:
      runs-on: ubuntu-latest
      steps:
        - name: Docker Login
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}