name: Build and Push Docker images

on:
    push:
    workflow_dispatch: 

jobs:
    docker-login:
      runs-on: ubuntu-latest
      steps:
        - name: Docker Login
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
    ghcr-login:
      needs: docker-login
      runs-on: ubuntu-latest
      steps:    
        - name: GHCR Login
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
    docker-build:
      needs: [docker-login,ghcr-login]
      runs-on: ubuntu-latest
      steps:
        - name: Docker image Build
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: |
              ${{ vars.DOCKER_USERNAME }}/test:${{ github.sha }}

    container-test:
      needs: [docker-login,ghcr-login,docker-build]
      runs-on: ubuntu-latest
      steps:
        - name: Docker Container Run
          runs: |
            docker images
            docker run -d \
            ${{ vars.DOCKER_USERNAME }}/test:${{ github.sha }}
