name: Build and Push Docker images

on:
    push:
    workflow_dispatch: 

jobs:
    docker login:
        - name: Docker Login
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ vars.DOCKER_PASSWORD }}