name: My First Workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Code Chekout
          uses: actions/checkout@v4
        - name: Welcome to Repo
          run: echo "Hello World"